apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
spec:
  selector:
    matchLabels:
      app: netflix-app
  template:
    metadata:
      labels:
        app: netflix-app
    spec:
      containers:
      - name: netflix-app
        image: quay.io/omidiyanto/netflix-app:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: netflix-app
spec:
  selector:
    app: netflix-app
  ports:
  - port: 8182
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netflix-app
  labels:
    name: netflix-app
spec:
  rules:
  - host: netflix-app.omidiyanto.my.id
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: netflix-app
            port:
              number: 8182
